package com.pergamon.core.enums;

public enum TransactionType {
	CREATE_ADMIN,//0
	UPDATE_ADMIN,//1
	DELETE_ADMIN,//2
	CREATE_VISITOR,//3
	UPDATE_VISITOR,//4
	DELETE_VISITOR,//5
	TIME_REQUEST,//6
	SEND_FEEDBACK,//7
	ADD_BARROWED,//8
	TAKE_BARROWED,//9
	DONATION,//10
	ADD_BOOK,//11
	UPDATE_BOOK,//12
	DELETE_BOOK,//13
	REGISTER_VISITOR_REQUEST, //14
	REGISTER_VISITOR_ACCEPT,//15
	REGISTER_VISITOR_REJECT//16
	
	
	
}
