spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: system
    password: quslivendus
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

axon:
  axonserver:
    enabled: false

storage:
  location: /var/www/photostore/images/  
  
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always